### ISSUE TITLE
Faulty syntax highlighting for numbers

### ISSUE THREAD

**Issue by jlcrochet** [rhysd/vim-crystal#73]
I recently noticed some small edge cases related to highlighting numbers that are not being handled properly, IMO:

1. Certain notations are highlighted that don't actually compile in Crystal:

   * `0d`- and `0D`-style decimal integers: `0d123 0D123`
   * `0X`/`0O`/`0B`-style hexadecimal/octal/binary integers: `0XABC 0O123 0B101`

    These notations are supported by Ruby, but not by Crystal. In my opinion, if they don't compile, they shouldn't be highlighted.

2. `-123` is highlighted as a `crystalInteger`, but `+123` is not.

3. For floats that use scientific notation, `123e-2` is highlighted correctly, but `123_e-2` isn't.

4. 8-, 16-, and 128-bit integer literals aren't highlighted properly. For example, `1u32` and `1u64` are highlighted, but `1u8`, `1u16`, and `1u128` aren't.

I was wondering if you would accept a PR to fix these issues.

**Comment by rhysd** [comment]
Thank you for reporting this. It seems that some syntax might be changed since this plugin had been created around numeric literals.

At 13673c0, I believe all bugs you kindly pointed out were fixed. I confirmed fixes as follows:

<img width="681" alt="スクリーンショット 2020-02-09 22 01 12" src="https://user-images.githubusercontent.com/823277/74102550-c8d08b80-4b87-11ea-8f2e-5c76b38e7185.png">

If I missed some points, please let me know.

**Comment by rhysd** [comment]
I decided not to highlight unary `+` and `-` specially since it is just an operator. If `+` of `+d` is not highlighted, `+` of `+42` also should not be highlighted consistently.

**Comment by jlcrochet** [comment]
Looks great to me, although there are a couple of cases in my own test file that are missed by this.

The following should be highlighted:
* `123_e2_`
* `123e_2`
* `0x_123_`
* `0___`

The following shouldn't be:
* Unary `-` in floats: `-1.0`
* `0o123_f32`, since octal integers can't be cast as floats

For reference, this was my own attempt at fixing these (sorry if all the variables make it harder to read):

```viml
let s:dec_int = '\%(0_*\|[1-9]\%(_*\d_*\)*\)'
let s:hex_int = '0x\%(_*\x_*\)\+'
let s:oct_int = '0o\%(_*\o_*\)\+'
let s:bin_int = '0b\%(_*[01]_*\)\+'
let s:float   = s:dec_int.'\.'.s:dec_int

let s:int_size   = '[iu]\%(8\|16\|32\|64\|128\)'
let s:float_size = '[fF]\%(32\|64\)'
let s:scientific = '[eE][+-]\=\%(_*\d_*\)\+'

function! s:optional(re)
  return '\%('.a:re.'\)\='
endfunction

function! s:bounded(re)
  return '\<\%('.a:re.'\)\>'
endfunction

function! s:or(...)
  return '\%('.join(a:000, '\|').'\)'
endfunction

exec 'syn match crystalInteger "' . s:bounded(s:or(s:dec_int, s:hex_int, s:oct_int, s:bin_int) . s:optional(s:int_size)) . '" display'

exec 'syn match crystalFloat "' . s:bounded(s:float) . '" display'
exec 'syn match crystalFloat "' . s:bounded(s:or(s:dec_int, s:float) . s:float_size) . '" display'
exec 'syn match crystalFloat "' . s:bounded(s:or(s:dec_int, s:float) . s:scientific . s:optional(s:float_size)) . '" display'
```

**Comment by rhysd** [comment]
Thank you for the failure cases. I fixed them at d558944, f80e29b and 2c44e33.

**Comment by jlcrochet** [comment]
I hope I'm not bothering you with this, but there are still a few cases that are having issues.

Here are the test cases that I was using (the ones marked with `XXX` are the ones that are still failing):

```
# Should highlight:
123
+123
-123
123_e2__
123e_2
123_E-123_456
123_f32
-123_e-_22_432____F32  # XXX
+123_E-22_432_f32
0___
0
123e-22F32  # XXX
123_e-22
123E2
123E2f32
0b1001010
-0b10
0b10101_u8
0b1010_i128
0o123
0o123_u8
-0o0123
0o123u32
0x123afAF
0x_123_
0_123__  # XXX
0_123_.0_123_  # XXX

# Shouldn't highlight:
0d123
123_U8
123_I128
0o123_f32  # XXX
0b101f32  # XXX
0O123
0o123U32
0o123f32  # XXX
0o123e2
0o12389
0B10101
-0b10232
1U8
1_I128
0d123
0123

# On these, the unary `-` is still being highlighted:
-1.0e-2_f32
-123e-2
-1.0
```

**Comment by rhysd** [comment]
```crystal
# Shouldn't highlight:
0o123_f32  # XXX
0b101f32  # XXX
0o123f32  # XXX
```

I did not know this. Isn't this a bug of Crystal? `123f32` is valid but `0o123f32` and `0b101f32` are not supported looks weird to me. Though `0x123f64` should not be allowed because 'f' is a part of hex decimal characters.

```crystal
0_123__
0_123_.0_123_
```

I did not notice that `0_` is permitted though it also looks weird too. `0_123` should be the same as `0123` and `0123` is not allowed.

```crystal
123e-22F32  # XXX
-123_e-_22_432____F32  # XXX
```

I also did not know these since I confirmed `U8` suffix was invalid.

@Marzipanzerfaust Did you find any issue for these inconsistency in `crystal-lang/crystal` repository? If not, I want to create an issue there before fixing them.

**Comment by rhysd** [comment]
> ```
> # Shouldn't highlight:
> 0o123_f32  # XXX
> 0b101f32  # XXX
> 0o123f32  # XXX
> ```
> I did not know this. Isn't this a bug of Crystal? 123f32 is valid but 0o123f32 and 0b101f32 are not supported looks weird to me. Though 0x123f64 should not be allowed because 'f' is a part of hex decimal characters.

I understood the reason. Numbers prefixed by `0o` and `0b` don't support floating numbers (`0b101.01` is not allowed) so `f32` and `f64` are not available. I'll fix this.

**Comment by rhysd** [comment]
> I also did not know these since I confirmed U8 suffix was invalid.

This also seems an intended behavior. I checked the lexer implementation:

https://github.com/crystal-lang/crystal/blob/fc9e15c568576770162587f7baa956aa5a6c2cd5/src/compiler/crystal/syntax/lexer.cr#L1437-L1480

`u` and `i` with only lowercase are accepted for integers, but `f` is accepted for both uppercase and lowercase.

**Comment by rhysd** [comment]
I found another edge case:

```crystal
# Should highlight
0_u42
```

and this is actually used in real-world. I'll fix it.
